### ISSUE TITLE
It's broken

### ISSUE THREAD

**Issue by ErikLentz** [CompChris/test-repo-cc#2]
How do I fix? Kthx

**Comment by WesCook** [comment]
https://www.youtube.com/watch?v=-WmGvYDLsj4

**Comment by ErikLentz** [comment]
What does this mean? Do I have a virus?

![screenshot 2017-11-10 at 1 19 27 pm](https://user-images.githubusercontent.com/7536439/32674694-e42c689a-c619-11e7-8d49-177f943d6aa8.png)
